version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.0.14
      - image: cimg/mariadb:10.6.4
    working_directory: ~/laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1
      - run: composer require --dev "orchestra/testbench"
      - save_cache:
          key: composer-v1
          paths:
            - vendor
      - run: sleep 100000
      - run: ./vendor/bin/phpunit tests/TestCase.php
