version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.0.14
      - image: cimg/mariadb:10.6.4
    working_directory: ~/laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1
      - run: composer require "laravel/framework:^8.0"
      - run: composer require "orchestra/testbench:^6.0" --dev
      - save_cache:
          key: composer-v8
          paths:
            - vendor
      - run: ./vendor/bin/phpunit tests/TestCase.php
